# 'version' is removed to fix the warning
networks:
  attendance-network:
    driver: bridge

volumes:
  mysql-data:

services:
  # 1. Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - attendance-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Fixes the MYSQL_ROOT_PASSWORD warning
      MYSQL_DATABASE: attendance_db
    ports:
      - "3307:3306" # Port 3307 on your machine
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Eureka Server (Starts first)
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    networks:
      - attendance-network
    ports:
      - "8761:8761"
    # No 'depends_on' or 'environment', it starts independently
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      start_period: 20s
      timeout: 5s
      retries: 5

  # 3. Config Server (Waits for Eureka)
  config-server:
    image: ammare03/config-server:latest
    container_name: config-server
    networks:
      - attendance-network
    ports:
      - "8088:8088"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      eureka-server: # Waits for eureka to be healthy
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      interval: 10s
      start_period: 20s
      timeout: 5s
      retries: 5

  # 4. User Service
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    networks:
      - attendance-network
    ports:
      - "8081:8081"
    environment:
      # FIX: Tells service where to find config-server
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/attendance_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  # 5. Course Service
  course-service:
    build:
      context: ./course-service
    container_name: course-service
    networks:
      - attendance-network
    ports:
      - "8082:8082"
    environment:
      # FIX: Tells service where to find config-server
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/attendance_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  # 6. Attendance Service
  attendance-service:
    build:
      context: ./attendance-service
    container_name: attendance-service
    networks:
      - attendance-network
    ports:
      - "8083:8083"
    environment:
      # FIX: Tells service where to find config-server
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/attendance_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  # 7. Reporting Service
  reporting-service:
    build:
      context: ./reporting-service
    container_name: reporting-service
    networks:
      - attendance-network
    ports:
      - "8084:8084"
    environment:
      # FIX: Tells service where to find config-server
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      
  # 8. API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    networks:
      - attendance-network
    ports:
      - "8089:8080" # Port 8089 on your machine
    environment:
      # FIX: Tells service where to find config-server
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      user-service:
        condition: service_started
      course-service:
        condition: service_started
      attendance-service:
        condition: service_started
      reporting-service:
        condition: service_started

  # 9. Frontend
  attendance-frontend:
    build:
      context: ./attendance-frontend
    container_name: attendance-frontend
    networks:
      - attendance-network
    ports:
      - "3000:80"
    depends_on:
      - api-gateway