apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: attendance-system
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: IMAGE_PLACEHOLDER_EUREKA_SERVER
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: attendance-system
  labels:
    app: eureka-server
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: eureka-server
