# 04-microservices.yaml
# 1. User Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: attendance-system
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z config-server 8088; do echo waiting for config-server; sleep 2; done;']
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka-server; sleep 2; done;']
      containers:
        - name: user-service
          image: IMAGE_PLACEHOLDER_USER_SERVICE
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8088"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: attendance-system
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---
# 2. Course Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: attendance-system
  labels:
    app: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z config-server 8088; do echo waiting for config-server; sleep 2; done;']
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka-server; sleep 2; done;']
      containers:
        - name: course-service
          image: IMAGE_PLACEHOLDER_COURSE_SERVICE
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8088"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: attendance-system
  labels:
    app: course-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP

---
# 3. Attendance Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
  namespace: attendance-system
  labels:
    app: attendance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z config-server 8088; do echo waiting for config-server; sleep 2; done;']
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka-server; sleep 2; done;']
      containers:
        - name: attendance-service
          image: IMAGE_PLACEHOLDER_ATTENDANCE_SERVICE
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8088"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: attendance-system
  labels:
    app: attendance-service
spec:
  selector:
    app: attendance-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

---
# 4. Reporting Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  namespace: attendance-system
  labels:
    app: reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z config-server 8088; do echo waiting for config-server; sleep 2; done;']
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka-server; sleep 2; done;']
      containers:
        - name: reporting-service
          image: IMAGE_PLACEHOLDER_REPORTING_SERVICE
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8088"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: attendance-system
  labels:
    app: reporting-service
spec:
  selector:
    app: reporting-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP